# retexo/core/scriba.py
"""
Scriba: replays a script and checks it reproduces the reuse.

Scriba shares no alignment code with the oracle. That independence is the
point: a verifier built from the machinery that produced a script can only
re-confirm it, whereas Scriba can judge a script from any source, including
one generated by a model.

Two failure modes are reported separately. A script may be **invalid** — it
writes a position twice, consumes a source token twice, leaves a gap — or it
may be valid but **not reproduce** the reuse. A model emitting unparseable
output is failing differently from one emitting a well-formed but wrong
transformation, and collapsing the two hides which problem a system has.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional, Sequence

from retexo.core.normalize import normalize
from retexo.operations import OperationRegistry, Role
from retexo.core.script import EditScript

# =============================================================================
# Validity
# =============================================================================


@dataclass(frozen=True)
class Validity:
    """The outcome of checking a script's structure, before executing it."""

    ok: bool
    problems: List[str] = field(default_factory=list)

    def __bool__(self) -> bool:
        return self.ok


# =============================================================================
# Scriba
# =============================================================================


class Scriba:
    """Executes and verifies edit scripts.

    Example:
        ```python
        scriba = Scriba()
        scriba.execute(script, source_tokens)      # -> reuse tokens
        scriba.verify(script, source_tokens, reuse_tokens)
        ```
    """

    def __init__(self, registry: Optional[OperationRegistry] = None):
        self.registry = registry or OperationRegistry.default()

    # ---------- Public API ----------

    def validate(self, script: EditScript, source_length: Optional[int] = None) -> Validity:
        """Check the script's structure without executing it."""
        problems: List[str] = []
        if source_length is None:
            source_length = len(script.source_tokens)

        written: dict = {}
        consumed: dict = {}
        for op in script.operations:
            role = self.registry[op.tag].role
            if role is Role.MARKER:
                continue
            for index in op.target_indices:
                if index in written:
                    problems.append(f"position {index} written twice ({written[index]}, {op.tag})")
                written[index] = op.tag
            for index in op.source_indices:
                if index in consumed:
                    problems.append(f"source {index} consumed twice ({consumed[index]}, {op.tag})")
                consumed[index] = op.tag
                if not 0 <= index < source_length:
                    problems.append(f"source index {index} out of range")

        if written:
            expected = set(range(max(written) + 1))
            missing = sorted(expected - set(written))
            if missing:
                problems.append(f"positions never written: {missing}")

        return Validity(ok=not problems, problems=problems)

    def execute(self, script: EditScript, source_tokens: Sequence[str]) -> List[str]:
        """Replay a script and return the tokens it produces.

        Raises:
            ValueError: If the script is structurally invalid. Call
                :meth:`validate` first when malformed input is expected.
        """
        validity = self.validate(script, len(source_tokens))
        if not validity:
            raise ValueError("invalid script: " + "; ".join(validity.problems))

        produced: dict = {}
        for op in script.writing_operations():
            for index, token in zip(op.target_indices, op.target_tokens):
                produced[index] = token
        return [produced[i] for i in sorted(produced)]

    def verify(
        self,
        script: EditScript,
        source_tokens: Sequence[str],
        target_tokens: Sequence[str],
    ) -> bool:
        """Whether replaying the script on the source reproduces the reuse."""
        try:
            produced = self.execute(script, source_tokens)
        except ValueError:
            return False
        return [normalize(t) for t in produced] == [normalize(t) for t in target_tokens]
